services:
  - type: web
    name: form-api
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PHP_VERSION
        value: "8.2"
    healthCheckPath: /test.php
    autoDeploy: true
